apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-chongya-ng
  labels:
    app: web-chongya-ng  
spec:
  selector:
    matchLabels:
      app: web-chongya-ng 
  replicas: 3 
  template: 
    metadata:
      labels:
        app: web-chongya-ng     
    spec:
      containers:
        - name: nginx
          image: icydoge/web:web-chongya-ng-4404728
          ports:
          - containerPort: 8080 
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-chongya-ng
spec:
  ports:
  - port: 8080
  selector:
    app: web-chongya-ng
